config/routes.rb
Rails.application.routes.draw do

  root :to => 'users#index'
  resources :users
  resources :recipes, except: [:index] do
    resources :comments, only: [:create, :destroy, :index]
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates :user_id, uniqueness: { scope: :recipe_id }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates :body, presence: true, length: { maximum: 65_535 }
end

app/models/recip.rb
class Recip < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user

  mount_uploader :recipe_image, RecipeImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_recipes, through: :bookmarks, source: :recipe

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true, length: { maximum: 255 }

  def own?(object)
    id == object.user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all
    
  end

  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_back(fallback_location: root_path)  #コメント送信後は、一つ前のページへリダイレクトさせる。
    else
      redirect_back(fallback_location: root_path)  #同上
    end
  end

  def destroy

  end


  private

  def comment_params
    params.require(:comment).permit(:body,:recipe_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit
    @recipe = current_user.recipes.find(params[:id])
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = current_user.recipes.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipes_path
    else
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :body, :recipe_image)
  end
end

app/controllers/user_sessions_controller.rb
# app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_back_or_to(:recipes, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :require_login, only: [:index, :new, :create]

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    
    binding.pry
    
    @user = User.new(user_params)

    if @user.save
      redirect_to(login_path, notice: 'User was successfully created')
    else
      render :new
      flash.now[:notice] = 'Error'
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/index.html.erb
<% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user.name %></td>
        <td><%= comment.body %></td>
        <td><%= link_to "削除",  recipe_comment_path(comment, comment), method: :delete %></td>
      </tr>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutorial</title>
      <%= stylesheet_link_tag    "application" %>
      <%= javascript_pack_tag "application" %>
      <%= csrf_meta_tags %>
  </head>
  <body>

  <div>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>

  <div class="mx-5" style="margin-top: 50px">
    <%= yield %>
  </div>

  </body>
</html>

app/views/recipes/_crud_menus.html.erb
<ul class='crud-menu-btn list-inline float-right'>
  <li class="list-inline-item">
    <%= link_to edit_recipe_path(recipe), id: "button-edit-#{recipe.id}" do %>
      <%= icon 'fa', 'pen' %>
    <% end %>
  </li>
  <li class="list-inline-item">
    <%= link_to recipe_path(recipe), method: :delete, id: "button-delete-#{recipe.id}", data: {confirm: '削除しますか？'} do %>
      <%= icon 'fas', 'trash' %>
    <% end %>
  </li>
</ul>

app/views/recipes/_recipe.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="recipe-id-1">
      <div class="card">
      <%- if recipe.recipe_image_url.nil? %>
        <%= image_tag 'sample.jpg', class: "card-img-top", width:"300", height:"200"%>
      <% else %>
        <%= image_tag recipe.recipe_image_url, class: "card-img-top", width:"300", height:"200"%>
      <% end %>
      <div class="card-body">
        <h4 class="card-title d-inline">
          <%= link_to recipe.title, recipe_path(recipe) %>
        </h4>
        <% if current_user.own?(recipe) %>
          <%= render 'crud_menus', recipe: recipe %>
        <% end %>
        <ul class="list-inline">
          <li class="list-inline-item"><i class="far fa-user"></i><%= recipe.user.name %></li>
          <li class="list-inline-item"><i class="far fa-calendar"></i><%= l recipe.created_at, format: :long %></li>
        </ul>
        <p class="card-text"><%= recipe.body %></p>
      </div>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Recipe#edit</h1>

<%= form_with model: @recipe, local: true do |f| %>
<div>
    <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
</div>
<div>
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 10 %>
</div>
    <%= f.submit 'レシピ編集' %>
<% end %>

app/views/recipes/index.html.erb
<h1>レシピ一覧</h1>
<div class="container pt-3">
  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @recipes.present? %>
          <%=  render @recipes %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row" >
  </div>
</div>

app/views/recipes/new.html.erb
<h1>Recipe#new</h1>

<%= form_with model: @recipe, local: true do |f| %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div>
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 10 %>
    </div>
    <div class="form-group">
		<%= f.label :recipe_image %>
		<%= f.file_field :recipe_image, class: 'form-control mb-3', accept: 'image/*' %>
        <%= f.hidden_field :recipe_image_cache %>
	</div>
    <%= f.submit 'レシピ投稿' %>
<% end %>

app/views/recipes/show.html.erb
<% content_for(:title, @recipe.title) %>
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <!-- 掲示板内容 -->
      <article class="card">
        <div class="card-body">
          <div class='row'>
            <div class='col-md-3'>
              <%= image_tag 'sample.jpg', class: "card-img-top img-fluid", size: '300x200' %>
            </div>
            <div class='col-md-9'>
              <h3 style='display: inline;'><%= @recipe.title %></h3>
              <%= render 'crud_menus', recipe: @recipe if current_user.own?(@recipe)%>
              <ul class="list-inline">
                <li class="list-inline-item"><%= "by #{@recipe.user.name}" %></li>
                <li class="list-inline-item"><%= l @recipe.created_at, format: :long %></li>
              </ul>
            </div>
          </div>
          <%= simple_format(@recipe.body) %>
        </div>
      </article>
    </div>
  </div>

</div>

app/views/user_sessions/_form.html.erb
<%= form_with url: login_path, method: :post do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Login" %>
  </div>
  <div class="field" id="star">
   <%= f.label :star,'評価 ', class:'col-md-3 col-form-label' %>
   <%= f.hidden_field :star, id: :review_star %>
</div>

<script>
console.log('aaa')
  $('#star').raty({
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',

    scoreName: 'comment[star]',
    half: false,
  });
</script>  
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="container">
  <div class="row">
    <div class=" col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1>ログイン</h1>
      <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, autofocus: true, class: "form-control", id: 'email' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, autofocus: true, class: "form-control", id: 'password' %>
        </div>
        <div class="actions">
          <%= f.submit "ログイン" , class: 'btn-prymary' %>
        </div>
      <% end %>
      <div class='text-center'>
        <%= link_to '登録ページへ', new_user_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
# app/views/users/_form.html.erb
<%= form_with model: @user, method: :post do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
     <%= f.label :password_confirmation %><br />
     <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Register" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1>ユーザー登録</h1>
      <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :first_name, autofocus: true, class: "form-control", id: "user_first_name" %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, autofocus: true, class: "form-control", id: 'user_email' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, autofocus: true, class: "form-control", id: 'user_password' %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, autofocus: true, class: "form-control", id: 'user_password_confirmation' %>
        </div>
        <div class="actions">
          <%= f.submit "登録" , class: 'btn-prymary' %>
        </div>
      <% end %>
      <div class='text-center'>
        <%=link_to 'ログインページへ', login_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Crypted password:</strong>
  <%= @user.crypted_password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>